spring.application.name=dev-service

# Conexion a tu MySQL de siempre
spring.datasource.url=jdbc:mysql://localhost:3306/dev_manager
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate para que no borre tus datos actuales
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=angel
spring.security.user.password=12345